database:
  path: "metadata.db"

proxy:
  enabled: false
  address: ""

google_translate:
  api_key: ""
  project_id: ""

video:
  output_dir: "downloads"
  subtitle_dir: "subtitles"
  processed_dir: "processed"